baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo Blog'

[params]
    homeText = "This is my Hugo blog."
    dateFormat = "Jan 1, 2005"

[permalinks]
    blog = "/:filename/"

    # See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[taxonomies]
  tag = "tags"