baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Matt Schultz'

[params]


[permalinks]
    resume = "/:filename/"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    pre = "edit"
    url = "/mws/"
    weight = 3
  [[menu.main]]
    name = "Contact"
    pre = "mail"
    url = "mailto:matt@mwschultz.com"
    weight = 3
  [[menu.main]]
    name = "Github"
    pre = "github"
    url = "https://github.com/mwschultz"
    weight = 3
  [[menu.main]]
    name = "LinkedIn"
    pre = "linkedin"
    url = "https://www.linkedin.com/in/mwschult/"
    weight = 3
  [[menu.main]]
    name = "Resume (PDF)"
    pre = "file-text"
    url = "/resume.pdf"
    weight = 3
