languageCode = 'en-us'
title = 'Matt Schultz'


[params]


[permalinks]
    resume = "/:filename/"
    portfolio = "/:filename/"


[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    pre = "edit"
    url = "/mws/"
    weight = 3
  [[menu.main]]
    name = "Github"
    pre = "github"
    url = "https://github.com/mwschultz"
    weight = 2
  [[menu.main]]
    name = "LinkedIn"
    pre = "linkedin"
    url = "https://www.linkedin.com/in/mwschult/"
    weight = 5
  [[menu.main]]
    name = "Resume (PDF)"
    pre = "file-text"
    url = "/files/resume.pdf"
    weight = 4
  [[menu.main]]
    name = "Example Apps (Portfolio)"
    pre = "zap"
    url = "/folio/"
    weight = 6
